services:
  db:
    image: postgres:16-alpine
    container_name: enclave_db
    restart: always
    environment:
      POSTGRES_USER: romarinhoBraisa
      POSTGRES_PASSWORD: brahmasimskolnao
      POSTGRES_DB: enclave_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
